=== YoelTeixeira/iut_xml/tp1/dtd/presentation.dtd
<!ELEMENT présentation (en-tête,diapositive+)>
<!ELEMENT en-tête (modèle+)>

<!ELEMENT modèle EMPTY>
<!ATTLIST modèle couleur CDATA #REQUIRED>
<!ATTLIST modèle taille CDATA #REQUIRED>

<!ELEMENT diapositive (titre,corps)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT corps (bloc+)>
<!ELEMENT bloc (paragraphe|liste|image)>
<!ELEMENT paragraphe (#PCDATA|gras|italique|couleur)*>

<!ELEMENT gras (#PCDATA)>
<!ATTLIST gras couleur CDATA #IMPLIED>

<!ELEMENT italique (#PCDATA)>
<!ATTLIST italique couleur CDATA #IMPLIED>

<!ELEMENT couleur (#PCDATA)>
<!ELEMENT image EMPTY>
<!ELEMENT liste (item+)>
<!ELEMENT item (paragraphe+|liste)*>

=== YoelTeixeira/iut_xml/tp1/dtd/presentation.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE présentation SYSTEM "presentation.dtd">

<présentation xmlns="urn:presentation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="urn:presentation presentation.xsd">
	<en-tête>
		<modèle couleur="#FFFF" taille="15"></modèle>
	</en-tête>
	<diapositive>
		<titre>Mon titre</titre>
		<corps>
			<bloc>
				<paragraphe>
					<gras>gras</gras>
					<italique>italique</italique>
					<couleur>couleur</couleur>
					Ma liste ci-dessous
				</paragraphe>
			</bloc>
			<bloc>
				<liste>
					<item>
						<paragraphe>Ma sous liste ci-dessous</paragraphe>
						<liste>
							<item>
								<paragraphe>Mon item <gras>en gras</gras></paragraphe>
							</item>
						</liste>
					</item>
				</liste>
			</bloc>
		</corps>
	</diapositive>
</présentation>
